# Generated by Django 5.2.17 on 2026-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='number_format',
        ),
        migrations.AddField(
            model_name='profile',
            name='heard_about',
            field=models.CharField(blank=True, choices=[('search_engine', 'Search engine'), ('social_media', 'Social media'), ('friend_family', 'Friend or family'), ('advert', 'Advert'), ('influencer', 'Influencer'), ('ai', 'AI assistant'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
