# Generated by Django 6.1.1 on 2026-09-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_feedback_admin_note_feedback_handled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='notify_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notify_community',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notify_interest',
            field=models.BooleanField(default=True),
        ),
    ]
