# Generated by Django 6.1.1 on 2026-09-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, default='', help_text='Optional page on the site, e.g. /resources', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('announcement', 'Announcement'), ('community', 'Community'), ('interest', 'Interest')], max_length=20)),
                ('event', models.CharField(choices=[('announcement', 'Announcement'), ('answered', 'Your question was answered'), ('accepted', 'Your answer was marked as the one that helped'), ('interest_seen', 'Your interest was seen by the team')], max_length=20)),
                ('text', models.CharField(blank=True, default='', max_length=300)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
