# Generated by Django 5.2.17 on 2026-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='link',
            field=models.URLField(blank=True, help_text='A resource on another website. Leave empty if you upload a file.', max_length=500),
        ),
    ]
