# Generated by Django 5.2.17 on 2026-09-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_contentitem_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('topic', models.CharField(choices=[('tlevels', 'T Levels in general'), ('placements', 'Placements'), ('amazon', 'Amazon'), ('choosing', 'Choosing and applying'), ('study', 'Studying and assessment'), ('other', 'Something else')], default='tlevels', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_questions', to=settings.AUTH_USER_MODEL)),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_questions', to='content.pathway')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.CharField(blank=True, default='', max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.question')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Helpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='community.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='community.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='one_helpful_per_question'), models.UniqueConstraint(fields=('user', 'answer'), name='one_helpful_per_answer'), models.CheckConstraint(condition=models.Q(models.Q(('answer__isnull', True), ('question__isnull', False)), models.Q(('answer__isnull', False), ('question__isnull', True)), _connector='OR'), name='helpful_marks_one_post')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('personal', 'Shares personal details'), ('unkind', 'Unkind or bullying'), ('unsafe', "Worried about someone's safety"), ('wrong', 'Wrong or misleading'), ('spam', 'Spam or advertising'), ('other', 'Something else')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.question')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['resolved', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'question'), name='one_report_per_question'), models.UniqueConstraint(fields=('reporter', 'answer'), name='one_report_per_answer'), models.CheckConstraint(condition=models.Q(models.Q(('answer__isnull', True), ('question__isnull', False)), models.Q(('answer__isnull', False), ('question__isnull', True)), _connector='OR'), name='reports_one_post')],
            },
        ),
    ]
