# Generated by Django 5.2.17 on 2026-09-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
