# Generated by Django 5.2.17 on 2026-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionofinterest',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
