"""
The interest form became a tick box on an account, so the details it used to
ask for are now copied from the account instead, and every one of them is
optional: sign-up collects no real name and no email, and the pathway is
optional there too. Nothing existing loses data; the columns only get looser.
"""
# Generated by Django 5.2.17 on 2026-09-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentitem_link'),
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionofinterest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='expressionofinterest',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='expressionofinterest',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expressions_of_interest', to='content.pathway'),
        ),
        migrations.AlterField(
            model_name='expressionofinterest',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent or guardian'), ('teacher', 'Teacher or school')], max_length=10),
        ),
    ]
