# Generated by Django 6.1.1 on 2026-09-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_interest_becomes_an_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionofinterest',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
